import { absExercises } from "./components/ExercisesPage/exercises";
import { bicepsExercises } from "./components/ExercisesPage/exercises";
import { backExercises } from "./components/ExercisesPage/exercises";
import { chestExercises } from "./components/ExercisesPage/exercises";
import { calvesExercises } from "./components/ExercisesPage/exercises";
import { shoulderExercises } from "./components/ExercisesPage/exercises";
import { tricepsExercises } from "./components/ExercisesPage/exercises";
import { upperLegsExercises } from "./components/ExercisesPage/exercises";

const programs = [
  {
    programImage: "/./program-images/hypertrophy-for-starters.webp",
    name: "Hypertrophy for Starters",
    id:"hypertrophy-for-starters",
    difficulty: "Beginner",
    goal: "Bodybuilding",
    workoutsPerWeek: "3 Days",
    workoutDuration: "30-45 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Chest, Back, Abs" },
        { exercise: chestExercises[0], sets: 3, reps: 10, intensity: "RPE 8" },
        { exercise: backExercises[0], sets: 3, reps: 10, intensity: "RPE 8" },
        { exercise: absExercises[0], sets: 3, reps: 15, intensity: "RPE 8" },
      ],
      day2: [
        { name: "Day 2 - Biceps, Triceps, Calves" },
        { exercise: bicepsExercises[0], sets: 3, reps: 12, intensity: "RPE 8" },
        {
          exercise: tricepsExercises[0],
          sets: 3,
          reps: 12,
          intensity: "RPE 8",
        },
        { exercise: calvesExercises[0], sets: 3, reps: 15, intensity: "RPE 8" },
      ],
      day3: [
        { name: "Day 3 - Shoulders, Legs, Abs" },
        {
          exercise: shoulderExercises[0],
          sets: 3,
          reps: 10,
          intensity: "RPE 8",
        },
        {
          exercise: upperLegsExercises[0],
          sets: 3,
          reps: 12,
          intensity: "RPE 8",
        },
        { exercise: absExercises[1], sets: 3, reps: 15, intensity: "RPE 8" },
      ],
    },
  },
  {
    programImage: "/./program-images/big-3-for-novices.jpg",
    name: "Big 3 for Novices",
    id:"big-3-for-novices",
    difficulty: "Novice",
    goal: "Powerlifting",
    workoutsPerWeek: "4 Days",
    workoutDuration: "45-60 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Full Body" },
        { exercise: chestExercises[0], sets: 3, reps: 5, intensity: "RPE 8" },
        { exercise: backExercises[0], sets: 3, reps: 5, intensity: "RPE 8" },
        {
          exercise: upperLegsExercises[0],
          sets: 3,
          reps: 5,
          intensity: "RPE 8",
        },
      ],
      day2: [
        { name: "Day 2 - Full Body" },
        {
          exercise: upperLegsExercises[2],
          sets: 3,
          reps: 12,
          intensity: "RPE 8",
        },
        {
          exercise: tricepsExercises[0],
          sets: 3,
          reps: 12,
          intensity: "RPE 8",
        },
        { exercise: absExercises[0], sets: 3, reps: 15, intensity: "RPE 8" },
      ],
      day3: [
        { name: "Day 3 - Full Body" },
        { exercise: chestExercises[1], sets: 3, reps: 8, intensity: "RPE 8" },
        { exercise: backExercises[1], sets: 3, reps: 8, intensity: "RPE 8" },
        {
          exercise: upperLegsExercises[1],
          sets: 3,
          reps: 8,
          intensity: "RPE 8",
        },
      ],
      day4: [
        { name: "Day 4 - Full Body" },
        {
          exercise: upperLegsExercises[2],
          sets: 3,
          reps: 6,
          intensity: "RPE 8",
        },
        {
          exercise: tricepsExercises[0],
          sets: 3,
          reps: 15,
          intensity: "RPE 8",
        },
        { exercise: absExercises[3], sets: 3, reps: 15, intensity: "RPE 8" },
      ],
    },
  },
  {
    programImage: "/./program-images/peak-performance.jpg",
    name: "Peak Performance",
    id:"peak-performance",
    difficulty: "Intermediate",
    goal: "Powerbuilding",
    workoutsPerWeek: "5 Days",
    workoutDuration: "> 60 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Chest & Back" },
        { exercise: chestExercises[1], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[1], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: chestExercises[2], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[2], sets: 3, reps: 6, intensity: "RPE 9" },
      ],
      day2: [
        { name: "Day 2 - Arms & Abs" },
        {
          exercise: bicepsExercises[1],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[1],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: bicepsExercises[2],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[2],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        { exercise: absExercises[2], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
      day3: [
        { name: "Day 3 - Chest & Back" },
        { exercise: chestExercises[3], sets: 3, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[3], sets: 3, reps: 10, intensity: "RPE 9" },
        { exercise: chestExercises[4], sets: 3, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[4], sets: 3, reps: 10, intensity: "RPE 9" },
      ],
      day4: [
        { name: "Day 4 - Arms & Abs" },
        {
          exercise: bicepsExercises[3],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[3],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: bicepsExercises[4],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[4],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        { exercise: absExercises[4], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
      day5: [
        { name: "Day 5 - Shoulders, Legs & Abs" },
        {
          exercise: shoulderExercises[1],
          sets: 3,
          reps: 6,
          intensity: "RPE 9",
        },
        {
          exercise: shoulderExercises[2],
          sets: 3,
          reps: 10,
          intensity: "RPE 9",
        },
        {
          exercise: upperLegsExercises[3],
          sets: 3,
          reps: 15,
          intensity: "RPE 9",
        },
        {
          exercise: calvesExercises[4],
          sets: 3,
          reps: 20,
          intensity: "RPE 9",
        },
        { exercise: absExercises[0], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
    },
  },
  {
    programImage: "/./program-images/everyday-athlete.jpg",
    name: "Everyday Athlete",
    id:"everyday-athlete",
    difficulty: "Advanced",
    goal: "Bodyweight Fitness",
    workoutsPerWeek: "2 Days",
    workoutDuration: "30-45 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Full Body" },
        { exercise: chestExercises[9], sets: 3, reps: 8, intensity: "RPE 9" },
        { exercise: backExercises[0], sets: 3, reps: 8, intensity: "RPE 9" },
        { exercise: absExercises[4], sets: 3, reps: 8, intensity: "RPE 9" },
        {
          exercise: upperLegsExercises[6],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        { exercise: calvesExercises[4], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
      day2: [
        { name: "Day 2 - Full Body" },
        { exercise: chestExercises[9], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[0], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: absExercises[5], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: tricepsExercises[5], sets: 3, reps: 8, intensity: "RPE 9" },
        {
          exercise: upperLegsExercises[6],
          sets: 3,
          reps: 15,
          intensity: "RPE 9",
        },
      ],
    },
  },
  {
    programImage: "/./program-images/foundation-fitness.webp",
    name: "Foundation Fitness",
    id:"foundation-fitness",
    difficulty: "Beginner",
    goal: "Bodybuilding",
    workoutsPerWeek: "2 Days",
    workoutDuration: "< 30 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Full Body" },
        { exercise: chestExercises[4], sets: 3, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[4], sets: 3, reps: 8, intensity: "RPE 9" },
        {
          exercise: upperLegsExercises[5],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        { exercise: absExercises[7], sets: 3, reps: 8, intensity: "RPE 9" },
        { exercise: calvesExercises[5], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
      day2: [
        { name: "Day 2 - Full Body" },
        { exercise: chestExercises[5], sets: 3, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[5], sets: 3, reps: 12, intensity: "RPE 9" },
        {
          exercise: upperLegsExercises[5],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        { exercise: bicepsExercises[5], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: tricepsExercises[5], sets: 3, reps: 8, intensity: "RPE 9" },
      ],
    },
  },
  {
    programImage: "/./program-images/big-lifts-blitz.webp",
    name: "Big Lifts Blitz",
    id:"big-lifts-blitz",
    difficulty: "Novice",
    goal: "Powerlifting",
    workoutsPerWeek: "3 Days",
    workoutDuration: "45-60 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Full Body" },
        {
          exercise: upperLegsExercises[11],
          sets: 3,
          reps: 6,
          intensity: "RPE 8",
        },
        { exercise: chestExercises[5], sets: 3, reps: 6, intensity: "RPE 8" },
        { exercise: backExercises[5], sets: 3, reps: 6, intensity: "RPE 8" },
      ],
      day2: [
        { name: "Day 2 - Full Body" },
        {
          exercise: upperLegsExercises[12],
          sets: 3,
          reps: 4,
          intensity: "RPE 8",
        },
        { exercise: bicepsExercises[3], sets: 3, reps: 4, intensity: "RPE 8" },
        {
          exercise: tricepsExercises[3],
          sets: 3,
          reps: 4,
          intensity: "RPE 8",
        },
        { exercise: calvesExercises[7], sets: 3, reps: 4, intensity: "RPE 8" },
      ],
      day3: [
        { name: "Day 3 - Full Body" },
        {
          exercise: upperLegsExercises[13],
          sets: 3,
          reps: 8,
          intensity: "RPE 8",
        },
        {
          exercise: shoulderExercises[7],
          sets: 3,
          reps: 8,
          intensity: "RPE 8",
        },
        {
          exercise: upperLegsExercises[14],
          sets: 3,
          reps: 12,
          intensity: "RPE 8",
        },
        { exercise: absExercises[7], sets: 3, reps: 15, intensity: "RPE 8" },
      ],
    },
  },
  {
    programImage: "/./program-images/power-physique.webp",
    name: "Power Physique",
    id:"power-physique",
    difficulty: "Intermediate",
    goal: "Bodybuilding",
    workoutsPerWeek: "4 Days",
    workoutDuration: "> 60 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Chest & Back" },
        { exercise: chestExercises[5], sets: 2, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[5], sets: 2, reps: 6, intensity: "RPE 9" },
        { exercise: chestExercises[6], sets: 3, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[6], sets: 3, reps: 6, intensity: "RPE 9" },
      ],
      day2: [
        { name: "Day 2 - Arms, Shoulders & Abs" },
        {
          exercise: bicepsExercises[5],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[5],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: shoulderExercises[6],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[6],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        { exercise: absExercises[6], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
      day3: [
        { name: "Day 3 - Chest & Back" },
        { exercise: chestExercises[7], sets: 2, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[7], sets: 2, reps: 10, intensity: "RPE 9" },
        { exercise: chestExercises[8], sets: 3, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[8], sets: 3, reps: 10, intensity: "RPE 9" },
      ],
      day4: [
        { name: "Day 4 - Arms, Shoulders & Abs" },
        {
          exercise: bicepsExercises[6],
          sets: 2,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[6],
          sets: 2,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: bicepsExercises[7],
          sets: 3,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: shoulderExercises[7],
          sets: 3,
          reps: 12,
          intensity: "RPE 9",
        },
        { exercise: absExercises[2], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
    },
  },
  {
    programImage: "/./program-images/advanced-conditioning.jpg",
    name: "Advanced Conditioning",
    id:"advance-conditioning",
    difficulty: "Advanced",
    goal: "Bodyweight Fitness",
    workoutsPerWeek: "4 Days",
    workoutDuration: "30-45 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Full Body" },
        { exercise: chestExercises[9], sets: 4, reps: 8, intensity: "RPE 10" },
        { exercise: backExercises[0], sets: 4, reps: 8, intensity: "RPE 10" },
        { exercise: absExercises[4], sets: 4, reps: 8, intensity: "RPE 10" },
        {
          exercise: upperLegsExercises[6],
          sets: 4,
          reps: 8,
          intensity: "RPE 10",
        },
      ],
      day2: [
        { name: "Day 2 - Full Body" },
        { exercise: chestExercises[9], sets: 4, reps: 6, intensity: "RPE 10" },
        { exercise: backExercises[0], sets: 3, reps: 6, intensity: "RPE 10" },
        { exercise: absExercises[5], sets: 3, reps: 6, intensity: "RPE 10" },
        {
          exercise: tricepsExercises[5],
          sets: 4,
          reps: 8,
          intensity: "RPE 10",
        },
        { exercise: absExercises[6], sets: 3, reps: 15, intensity: "RPE 10" },
        {
          exercise: calvesExercises[4],
          sets: 3,
          reps: 15,
          intensity: "RPE 10",
        },
      ],
      day3: [
        { name: "Day 3 - Upper Body" },
        { exercise: chestExercises[9], sets: 3, reps: 6, intensity: "RPE 10" },
        { exercise: backExercises[0], sets: 5, reps: 5, intensity: "RPE 10" },
        { exercise: absExercises[6], sets: 3, reps: 6, intensity: "RPE 10" },
        {
          exercise: tricepsExercises[0],
          sets: 3,
          reps: 8,
          intensity: "RPE 10",
        },
      ],
      day4: [
        { name: "Day 4 - Full Body" },
        { exercise: chestExercises[9], sets: 3, reps: 6, intensity: "RPE 10" },
        { exercise: backExercises[0], sets: 5, reps: 8, intensity: "RPE 10" },
        {
          exercise: upperLegsExercises[10],
          sets: 3,
          reps: 6,
          intensity: "RPE 10",
        },
        { exercise: absExercises[4], sets: 3, reps: 15, intensity: "RPE 10" },
      ],
    },
  },
  {
    programImage: "/./program-images/strength-surge.jpg",
    name: "Strength Surge",
    id:"strength-surge",
    difficulty: "Novice",
    goal: "Powerbuilding",
    workoutsPerWeek: "6 Days",
    workoutDuration: "45-60 Minutes",
    programStructure: {
      day1: [
        { name: "Day 1 - Chest & Back" },
        { exercise: chestExercises[7], sets: 2, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[7], sets: 2, reps: 6, intensity: "RPE 9" },
        { exercise: chestExercises[8], sets: 2, reps: 6, intensity: "RPE 9" },
        { exercise: backExercises[8], sets: 2, reps: 6, intensity: "RPE 9" },
      ],
      day2: [
        { name: "Day 2 - Arms & Abs" },
        {
          exercise: bicepsExercises[8],
          sets: 2,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[8],
          sets: 2,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: bicepsExercises[9],
          sets: 2,
          reps: 12,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[9],
          sets: 2,
          reps: 12,
          intensity: "RPE 9",
        },
        { exercise: absExercises[8], sets: 2, reps: 15, intensity: "RPE 9" },
      ],
      day3: [
        { name: "Day 3 - Shoulders & Legs" },
        {
          exercise: shoulderExercises[7],
          sets: 2,
          reps: 6,
          intensity: "RPE 9",
        },
        {
          exercise: shoulderExercises[6],
          sets: 2,
          reps: 10,
          intensity: "RPE 9",
        },
        {
          exercise: upperLegsExercises[10],
          sets: 2,
          reps: 15,
          intensity: "RPE 9",
        },
        {
          exercise: calvesExercises[4],
          sets: 2,
          reps: 20,
          intensity: "RPE 9",
        },
      ],
      day4: [
        { name: "Day 4 - Chest & Back" },
        { exercise: chestExercises[6], sets: 2, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[4], sets: 2, reps: 10, intensity: "RPE 9" },
        { exercise: chestExercises[6], sets: 2, reps: 10, intensity: "RPE 9" },
        { exercise: backExercises[4], sets: 2, reps: 10, intensity: "RPE 9" },
      ],
      day5: [
        { name: "Day 5 - Arms & Abs" },
        {
          exercise: bicepsExercises[6],
          sets: 2,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[4],
          sets: 2,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: bicepsExercises[5],
          sets: 2,
          reps: 8,
          intensity: "RPE 9",
        },
        {
          exercise: tricepsExercises[3],
          sets: 2,
          reps: 12,
          intensity: "RPE 9",
        },
        { exercise: absExercises[9], sets: 3, reps: 15, intensity: "RPE 9" },
      ],
      day6: [
        { name: "Day 6 - Shoulders & Legs" },
        {
          exercise: shoulderExercises[9],
          sets: 2,
          reps: 6,
          intensity: "RPE 9",
        },
        {
          exercise: shoulderExercises[8],
          sets: 2,
          reps: 10,
          intensity: "RPE 9",
        },
        {
          exercise: calvesExercises[3],
          sets: 2,
          reps: 15,
          intensity: "RPE 9",
        },
        {
          exercise: upperLegsExercises[8],
          sets: 2,
          reps: 15,
          intensity: "RPE 9",
        },
      ],
    },
  },
];

export default programs;
