const programs = [
  {
    programImage: "./program-image-placeholder.webp",
    name: "Hypertrophy for Starters",
    difficulty: "Beginner",
    goal: "Bodybuilding",
    workoutsPerWeek: "3 Days",
    workoutDuration: "30-45 Minutes",
  },
  {
    programImage: "./program-image-placeholder.webp",
    name: "Big 3 for Novices",
    difficulty: "Novice",
    goal: "Powerlifting",
    workoutsPerWeek: "4 Days",
    workoutDuration: "45-60 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Big But Boring",
    difficulty: "Intermediate",
    goal: "Powerbuilding",
    workoutsPerWeek: "5 Days",
    workoutDuration: "> 60 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Advanced Bodyweight Fitness",
    difficulty: "Advanced",
    goal: "Bodyweight Fitness",
    workoutsPerWeek: "6 Days",
    workoutDuration: "30-45 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Beginner Full Body",
    difficulty: "Beginner",
    goal: "Bodybuilding",
    workoutsPerWeek: "2 Days",
    workoutDuration: "< 30 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Novice Strength Training",
    difficulty: "Novice",
    goal: "Powerlifting",
    workoutsPerWeek: "3 Days",
    workoutDuration: "45-60 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Intermediate Muscle Building",
    difficulty: "Intermediate",
    goal: "Bodybuilding",
    workoutsPerWeek: "4 Days",
    workoutDuration: "> 60 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Advanced Conditioning",
    difficulty: "Advanced",
    goal: "Bodyweight Fitness",
    workoutsPerWeek: "5 Days",
    workoutDuration: "30-45 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Beginner Fat Loss",
    difficulty: "Beginner",
    goal: "Bodyweight Fitness",
    workoutsPerWeek: "3 Days",
    workoutDuration: "< 30 Minutes",
  },
  {
    programImage: "/program-image-placeholder.webp",
    name: "Novice Power Endurance",
    difficulty: "Novice",
    goal: "Powerbuilding",
    workoutsPerWeek: "6 Days",
    workoutDuration: "45-60 Minutes",
  },
];

export default programs;
